#!/bin/bash

# based on https://wiki.archlinux.org/index.php/Port_knocking#Client_script
# nmap must be installed

# usage
# knock ssh host root 777 888 999

PROG=$1
HOST=$2
USER=$3
TCPUDP=$4

if [ $TCPUDP == udp ] || [ $TCPUDP == UDP ] ;then
        PROTO=sU
  else
        PROTO=sT
fi

shift
for ARG in "$@"
do
done
$PROG $USER@$HOST
