#!/bin/bash

# nmap must be installed

# usage
# knock ssh host root 777 888 999

PROG=$1
HOST=$2
USER=$3
shift
for ARG in "$@"
do
        nmap -Pn --host-timeout 100 --max-retries 0 -p $ARG $HOST
done
$PROG $USER@$HOST
